<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9b020a0a757365722e70726f746f12047573657222360a0b5573657252" .
            "657175657374120a0a026964180120012805120c0a046e616d6518022001" .
            "2809120d0a05656d61696c18032001280922370a0c55736572526573706f" .
            "6e7365120a0a026964180120012805120c0a046e616d6518022001280912" .
            "0d0a05656d61696c180320012809221a0a0a5573657246696c746572120c" .
            "0a046e616d6518012001280932720a045573657212330a08476574557365" .
            "727312102e757365722e5573657246696c7465721a112e757365722e5573" .
            "6572526571756573742200300112350a0a4372656174655573657212112e" .
            "757365722e55736572526571756573741a122e757365722e557365725265" .
            "73706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}